name: Android Build

on:
  push:
    branches:
      - main  # 当推送到 `main` 分支时触发
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build with Gradle
        run: ./gradlew assembleRelease
#
#      - name: Package Assets
#        run: ./gradlew zipAssets
      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          tag_name: ${{ github.ref }} # 使用推送的标签作为版本号
          release_name: Release ${{ github.ref }}
          body: |
            自动生成的 Release Notes.
          draft: false
          prerelease: false
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/release/*.apk
#
#      - name: Upload Assets
#        uses: actions/upload-artifact@v2
#        with:
#          name: assets
#          path: app/build/outputs/assets/assets.zip
